version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      actions-all:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      docker-base-images:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/src/pgstac-migrate"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      python-all:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      rust-all:
        applies-to: version-updates
        patterns:
          - "*"
