services:
  pgstac:
    image: pgstac
    env_file:
      - .env
    build:
      context: .
      network: host
      dockerfile: docker/pgstac/Dockerfile
      target: pgstac
    platform: linux/amd64
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-username}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgis}
      - PGHOST=/var/run/postgresql
      - PGPORT=5432
      - PGUSER=${PGUSER:-username}
      - PGPASSWORD=${PGPASSWORD:-password}
      - PGDATABASE=${PGDATABASE:-postgis}
    ports:
      - "${PGPORT:-5439}:5432"
    volumes:
      - pgstac-pgdata:/var/lib/postgresql/data
    command: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h /var/run/postgresql -p 5432 -U ${PGUSER:-username} -d ${PGDATABASE:-postgis}"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
  pypgstac:
    image: pypgstac
    env_file:
      - .env
    build:
      context: .
      network: host
      dockerfile: docker/pypgstac/Dockerfile
      target: pypgstac
    platform: linux/amd64
    environment:
      - PGHOST=pgstac
      - PGPORT=5432
      - PGUSER=${PGUSER:-username}
      - PGPASSWORD=${PGPASSWORD:-password}
      - PGDATABASE=${PGDATABASE:-postgis}
    depends_on:
      pgstac:
        condition: service_healthy
volumes:
  pgstac-pgdata:
