-- Generated by pgpkg makemigration
-- Project: pgstac
-- From:    0.9.11
-- To:      unreleased
-- Review the diff before applying.

RESET ROLE;
DO $$
DECLARE
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname='postgis') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname='btree_gist') THEN
    CREATE EXTENSION IF NOT EXISTS btree_gist;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname='unaccent') THEN
    CREATE EXTENSION IF NOT EXISTS unaccent;
  END IF;
END;
$$ LANGUAGE PLPGSQL;

DO $$
  BEGIN
    CREATE ROLE pgstac_admin;
  EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;

DO $$
  BEGIN
    CREATE ROLE pgstac_read;
  EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;

DO $$
  BEGIN
    CREATE ROLE pgstac_ingest;
  EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;


GRANT pgstac_admin TO current_user;

-- Function to make sure pgstac_admin is the owner of items
CREATE OR REPLACE FUNCTION pgstac_admin_owns() RETURNS VOID AS $$
DECLARE
  f RECORD;
BEGIN
  FOR f IN (
    SELECT
      concat(
        oid::regproc::text,
        '(',
        coalesce(pg_get_function_identity_arguments(oid),''),
        ')'
      ) AS name,
      CASE prokind WHEN 'f' THEN 'FUNCTION' WHEN 'p' THEN 'PROCEDURE' WHEN 'a' THEN 'AGGREGATE' END as typ
    FROM pg_proc
    WHERE
      pronamespace=to_regnamespace('pgstac')
      AND proowner != to_regrole('pgstac_admin')
      AND proname NOT LIKE 'pg_stat%'
  )
  LOOP
    BEGIN
      EXECUTE format('ALTER %s %s OWNER TO pgstac_admin;', f.typ, f.name);
    EXCEPTION WHEN others THEN
      RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
    END;
  END LOOP;
  FOR f IN (
    SELECT
      oid::regclass::text as name,
      CASE relkind
        WHEN 'i' THEN 'INDEX'
        WHEN 'I' THEN 'INDEX'
        WHEN 'p' THEN 'TABLE'
        WHEN 'r' THEN 'TABLE'
        WHEN 'v' THEN 'VIEW'
        WHEN 'S' THEN 'SEQUENCE'
        ELSE NULL
      END as typ
    FROM pg_class
    WHERE relnamespace=to_regnamespace('pgstac') and relowner != to_regrole('pgstac_admin') AND relkind IN ('r','p','v','S') AND relname NOT LIKE 'pg_stat'
  )
  LOOP
    BEGIN
      EXECUTE format('ALTER %s %s OWNER TO pgstac_admin;', f.typ, f.name);
    EXCEPTION WHEN others THEN
      RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
    END;
  END LOOP;
  RETURN;
END;
$$ LANGUAGE PLPGSQL;
SELECT pgstac_admin_owns();

CREATE SCHEMA IF NOT EXISTS pgstac AUTHORIZATION pgstac_admin;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA pgstac to pgstac_admin;
GRANT ALL ON ALL TABLES IN SCHEMA pgstac to pgstac_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA pgstac to pgstac_admin;

ALTER ROLE pgstac_admin SET SEARCH_PATH TO pgstac, public;
ALTER ROLE pgstac_read SET SEARCH_PATH TO pgstac, public;
ALTER ROLE pgstac_ingest SET SEARCH_PATH TO pgstac, public;

GRANT USAGE ON SCHEMA pgstac to pgstac_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgstac GRANT SELECT ON TABLES TO pgstac_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgstac GRANT USAGE ON TYPES TO pgstac_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgstac GRANT ALL ON SEQUENCES TO pgstac_read;

GRANT pgstac_read TO pgstac_ingest;
GRANT ALL ON SCHEMA pgstac TO pgstac_ingest;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgstac GRANT ALL ON TABLES TO pgstac_ingest;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgstac GRANT ALL ON FUNCTIONS TO pgstac_ingest;

SET ROLE pgstac_admin;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_admin IN SCHEMA pgstac GRANT SELECT ON TABLES TO pgstac_read;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_admin IN SCHEMA pgstac GRANT USAGE ON TYPES TO pgstac_read;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_admin IN SCHEMA pgstac GRANT ALL ON SEQUENCES TO pgstac_read;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_admin IN SCHEMA pgstac GRANT ALL ON TABLES TO pgstac_ingest;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_admin IN SCHEMA pgstac GRANT ALL ON FUNCTIONS TO pgstac_ingest;
RESET ROLE;

SET ROLE pgstac_ingest;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_ingest IN SCHEMA pgstac GRANT SELECT ON TABLES TO pgstac_read;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_ingest IN SCHEMA pgstac GRANT USAGE ON TYPES TO pgstac_read;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_ingest IN SCHEMA pgstac GRANT ALL ON SEQUENCES TO pgstac_read;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_ingest IN SCHEMA pgstac GRANT ALL ON TABLES TO pgstac_ingest;
ALTER DEFAULT PRIVILEGES FOR ROLE pgstac_ingest IN SCHEMA pgstac GRANT ALL ON FUNCTIONS TO pgstac_ingest;
RESET ROLE;

SET SEARCH_PATH TO pgstac, public;
SET ROLE pgstac_admin;

DO $$
  BEGIN
    DROP FUNCTION IF EXISTS analyze_items;
  EXCEPTION WHEN others THEN
    RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;
DO $$
  BEGIN
    DROP FUNCTION IF EXISTS validate_constraints;
  EXCEPTION WHEN others THEN
    RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;

-- Install these idempotently as migrations do not put them before trying to modify the collections table


CREATE OR REPLACE FUNCTION collection_geom(content jsonb)
RETURNS geometry AS $$
    WITH box AS (SELECT content->'extent'->'spatial'->'bbox'->0 as box)
    SELECT
        st_makeenvelope(
            (box->>0)::float,
            (box->>1)::float,
            (box->>2)::float,
            (box->>3)::float,
            4326
        )
    FROM box;
$$ LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION collection_datetime(content jsonb)
RETURNS timestamptz AS $$
    SELECT
        CASE
            WHEN
                (content->'extent'->'temporal'->'interval'->0->>0) IS NULL
            THEN '-infinity'::timestamptz
            ELSE
                (content->'extent'->'temporal'->'interval'->0->>0)::timestamptz
        END
    ;
$$ LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION collection_enddatetime(content jsonb)
RETURNS timestamptz AS $$
    SELECT
        CASE
            WHEN
                (content->'extent'->'temporal'->'interval'->0->>1) IS NULL
            THEN 'infinity'::timestamptz
            ELSE
                (content->'extent'->'temporal'->'interval'->0->>1)::timestamptz
        END
    ;
$$ LANGUAGE SQL IMMUTABLE STRICT;
create sequence "pgstac"."item_fragments_id_seq";

drop function if exists "pgstac"."content_slim"(_item jsonb);


drop function if exists "pgstac"."search_rows"(_where text, _orderby text, partitions text[], _limit integer);

drop function if exists "pgstac"."where_stats"(inwhere text, updatestats boolean, conf jsonb);

alter table "pgstac"."search_wheres" drop constraint "search_wheres_pkey";

drop index if exists "pgstac"."search_wheres_partitions";

drop index if exists "pgstac"."search_wheres_pkey";

drop index if exists "pgstac"."search_wheres_where";

drop table "pgstac"."search_wheres";

create table "pgstac"."item_field_registry" (
    "collection" text not null,
    "path" text not null,
    "is_leaf" boolean default true,
    "value_kinds" text[] default '{}'::text[],
    "first_seen" timestamp with time zone not null default now(),
    "last_seen" timestamp with time zone not null default now()
);


create table "pgstac"."item_fragments" (
    "id" bigint not null default nextval('item_fragments_id_seq'::regclass),
    "collection" text not null,
    "hash" text not null,
    "content" jsonb not null,
    "created_at" timestamp with time zone not null default now()
);


create table "pgstac"."items_deleted_log" (
    "id" bigint generated always as identity not null,
    "item_id" text not null,
    "collection" text not null,
    "partition" text,
    "datetime" timestamp with time zone,
    "end_datetime" timestamp with time zone,
    "content_hash" text not null default ''::text,
    "deleted_at" timestamp with time zone not null default now()
);


alter table "pgstac"."items" add column "assets" jsonb default '{}'::jsonb;

alter table "pgstac"."items" add column "bbox" jsonb;

alter table "pgstac"."items" add column "content_hash" text not null default ''::text;

alter table "pgstac"."items" add column "eo_cloud_cover" double precision;

alter table "pgstac"."items" add column "eo_snow_cover" double precision;

alter table "pgstac"."items" add column "extra" jsonb;

alter table "pgstac"."items" add column "fragment_id" bigint;

alter table "pgstac"."items" add column "gsd" double precision;

alter table "pgstac"."items" add column "links" jsonb default '[]'::jsonb;

alter table "pgstac"."items" add column "pgstac_updated_at" timestamp with time zone not null default now();

alter table "pgstac"."items" add column "properties" jsonb default '{}'::jsonb;

alter table "pgstac"."items" add column "view_off_nadir" double precision;

alter table "pgstac"."items" add column "view_sun_azimuth" double precision;

alter table "pgstac"."items" add column "view_sun_elevation" double precision;

alter table "pgstac"."searches" add column "context_count" bigint;

alter table "pgstac"."searches" add column "created_at" timestamp with time zone default now();

alter table "pgstac"."searches" add column "name" text;

alter table "pgstac"."searches" add column "pinned" boolean not null default false;

alter table "pgstac"."searches" add column "statslastupdated" timestamp with time zone;

alter table "pgstac"."searches" alter column "hash" drop expression;

alter sequence "pgstac"."item_fragments_id_seq" owned by "pgstac"."item_fragments"."id";

CREATE INDEX item_field_registry_path_idx ON pgstac.item_field_registry USING btree (path);

CREATE UNIQUE INDEX item_field_registry_pkey ON pgstac.item_field_registry USING btree (collection, path);

CREATE UNIQUE INDEX item_fragments_collection_hash_key ON pgstac.item_fragments USING btree (collection, hash);

CREATE INDEX item_fragments_collection_idx ON pgstac.item_fragments USING btree (collection);

CREATE UNIQUE INDEX item_fragments_pkey ON pgstac.item_fragments USING btree (id);

CREATE INDEX items_deleted_log_deleted_at_idx ON pgstac.items_deleted_log USING btree (deleted_at);

CREATE UNIQUE INDEX items_deleted_log_pkey ON pgstac.items_deleted_log USING btree (id);

CREATE INDEX searches_lastused_anon_idx ON pgstac.searches USING btree (lastused) WHERE ((name IS NULL) AND (NOT pinned));

CREATE UNIQUE INDEX searches_name_key ON pgstac.searches USING btree (name);

alter table "pgstac"."item_field_registry" add constraint "item_field_registry_pkey" PRIMARY KEY using index "item_field_registry_pkey";

alter table "pgstac"."item_fragments" add constraint "item_fragments_pkey" PRIMARY KEY using index "item_fragments_pkey";

alter table "pgstac"."items_deleted_log" add constraint "items_deleted_log_pkey" PRIMARY KEY using index "items_deleted_log_pkey";

alter table "pgstac"."item_field_registry" add constraint "item_field_registry_collection_fkey" FOREIGN KEY ("collection") REFERENCES "pgstac"."collections"("id") ON DELETE CASCADE NOT VALID;

alter table "pgstac"."item_field_registry" validate constraint "item_field_registry_collection_fkey";

alter table "pgstac"."item_fragments" add constraint "item_fragments_collection_fkey" FOREIGN KEY ("collection") REFERENCES "pgstac"."collections"("id") ON DELETE CASCADE NOT VALID;

alter table "pgstac"."item_fragments" validate constraint "item_fragments_collection_fkey";

alter table "pgstac"."item_fragments" add constraint "item_fragments_collection_hash_key" UNIQUE using index "item_fragments_collection_hash_key";

-- items.fragment_id FK: added as VALID because PostgreSQL does not support
-- NOT VALID foreign keys on partitioned tables.
alter table "pgstac"."items" add constraint "items_fragment_id_fkey" FOREIGN KEY ("fragment_id") REFERENCES "pgstac"."item_fragments"("id");

alter table "pgstac"."searches" add constraint "searches_name_key" UNIQUE using index "searches_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION pgstac.extract_fragment(content jsonb, excluded_keys text[] DEFAULT '{id,geometry,collection,type}'::text[])
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
AS $function$
    SELECT content - COALESCE(excluded_keys, '{id,geometry,collection,type}'::text[]);
$function$
;

CREATE OR REPLACE FUNCTION pgstac.gc_anonymous_searches(retention_interval interval DEFAULT NULL::interval, conf jsonb DEFAULT NULL::jsonb)
 RETURNS bigint
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    WITH effective_retention AS (
        SELECT COALESCE(
            retention_interval,
            search_gc_retention_interval(conf)
        ) AS i
    ),
    deleted AS (
        DELETE FROM searches
        USING effective_retention
        WHERE
            name IS NULL
            AND NOT pinned
            AND lastused < now() - effective_retention.i
        RETURNING 1
    )
    SELECT count(*)::bigint FROM deleted;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.gc_deleted_items_log(retention_interval interval DEFAULT '30 days'::interval)
 RETURNS bigint
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT gc_deleted_items_log(retention_interval, 10000);
$function$
;

CREATE OR REPLACE FUNCTION pgstac.gc_deleted_items_log(retention_interval interval, batch_limit integer)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    deleted_count bigint := 0;
    batch_deleted bigint;
BEGIN
    LOOP
        batch_deleted := gc_deleted_items_log_batch(retention_interval, batch_limit);
        deleted_count := deleted_count + batch_deleted;
        EXIT WHEN batch_deleted = 0;
    END LOOP;

    RETURN deleted_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.gc_deleted_items_log_batch(retention_interval interval DEFAULT '30 days'::interval, batch_limit integer DEFAULT 10000)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    batch_deleted bigint;
BEGIN
    WITH to_delete AS (
        SELECT ctid
        FROM items_deleted_log
        WHERE deleted_at < now() - retention_interval
        ORDER BY deleted_at
        LIMIT GREATEST(COALESCE(batch_limit, 10000), 1)
    ),
    deleted AS (
        DELETE FROM items_deleted_log d
        USING to_delete td
        WHERE d.ctid = td.ctid
        RETURNING 1
    )
    SELECT count(*)::bigint INTO batch_deleted FROM deleted;

    RETURN batch_deleted;
END;
$function$
;

CREATE OR REPLACE PROCEDURE pgstac.gc_deleted_items_log_committed(IN retention_interval interval DEFAULT '30 days'::interval, IN batch_limit integer DEFAULT 10000)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    batch_deleted bigint;
BEGIN
    LOOP
        batch_deleted := gc_deleted_items_log_batch(retention_interval, batch_limit);
        EXIT WHEN batch_deleted = 0;
        COMMIT;
    END LOOP;
END;
$procedure$
;

CREATE OR REPLACE FUNCTION pgstac.gc_fragments(_collection text DEFAULT NULL::text, retention_interval interval DEFAULT '90 days'::interval)
 RETURNS TABLE(collection_id text, fragments_removed integer)
 LANGUAGE sql
AS $function$
    WITH deleted AS (
        DELETE FROM item_fragments f
        WHERE
            (_collection IS NULL OR f.collection = _collection)
            AND f.created_at < now() - retention_interval
            AND NOT EXISTS (SELECT 1 FROM items i WHERE i.fragment_id = f.id)
        RETURNING f.collection
    )
    SELECT collection, count(*)::int
    FROM deleted
    GROUP BY collection;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.gc_search_caches(retention_interval interval DEFAULT NULL::interval, conf jsonb DEFAULT NULL::jsonb)
 RETURNS jsonb
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT jsonb_build_object(
        'removed_searches',
        gc_anonymous_searches(retention_interval, conf)
    );
$function$
;

CREATE OR REPLACE FUNCTION pgstac.get_or_create_fragment(content jsonb, _collection text, excluded_keys text[] DEFAULT '{id,geometry,collection,type}'::text[])
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
    frag_content jsonb;
    frag_hash    text;
    frag_id      bigint;
BEGIN
    IF content IS NULL OR _collection IS NULL THEN
        RETURN NULL;
    END IF;

    frag_content := extract_fragment(content, excluded_keys);
    frag_hash    := pgstac_hash_fragment(frag_content);

    -- Insert-first: one round trip when the fragment is new.
    WITH ins AS (
        INSERT INTO item_fragments (collection, hash, content)
        VALUES (_collection, frag_hash, frag_content)
        ON CONFLICT (collection, hash) DO NOTHING
        RETURNING id
    )
    SELECT id INTO frag_id FROM ins;

    -- Fallback SELECT: one extra round trip only on the conflict path.
    IF frag_id IS NULL THEN
        SELECT id INTO frag_id
        FROM item_fragments
        WHERE collection = _collection AND hash = frag_hash;
    END IF;

    RETURN frag_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.items_delete_log_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    INSERT INTO items_deleted_log (
        item_id,
        collection,
        partition,
        datetime,
        end_datetime,
        content_hash
    )
    SELECT
        old_rows.id,
        old_rows.collection,
        (partition_name(old_rows.collection, old_rows.datetime)).partition_name,
        old_rows.datetime,
        old_rows.end_datetime,
        old_rows.content_hash
    FROM old_rows;

    RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.items_touch_triggerfunc()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    NEW.pgstac_updated_at := now();
    NEW.content_hash := encode(sha256(content_hydrate(NEW)::text::bytea), 'hex');
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.jsonb_field_rows(data jsonb, parent_path text DEFAULT ''::text, max_depth integer DEFAULT 20)
 RETURNS TABLE(path text, is_leaf boolean, value_kind text)
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
AS $function$
DECLARE
    k text;
    v jsonb;
    current_path text;
    jtype text;
BEGIN
    IF data IS NULL OR max_depth <= 0 THEN
        RETURN;
    END IF;
    jtype := jsonb_typeof(data);
    IF jtype = 'object' THEN
        FOR k, v IN SELECT * FROM jsonb_each(data) LOOP
            current_path := CASE WHEN parent_path = '' THEN k ELSE parent_path || '.' || k END;
            IF jsonb_typeof(v) IN ('object', 'array') THEN
                RETURN QUERY SELECT current_path, FALSE, jsonb_typeof(v);
                RETURN QUERY SELECT * FROM jsonb_field_rows(v, current_path, max_depth - 1);
            ELSE
                RETURN QUERY SELECT current_path, TRUE, jsonb_typeof(v);
            END IF;
        END LOOP;
    ELSIF jtype = 'array' THEN
        -- Walk array elements (e.g. arrays of nested objects); arrays of scalars
        -- are already handled as leaves in the object branch above.
        FOR v IN SELECT jsonb_array_elements(data) LOOP
            IF jsonb_typeof(v) = 'object' THEN
                RETURN QUERY SELECT * FROM jsonb_field_rows(v, parent_path, max_depth - 1);
            END IF;
        END LOOP;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.name_search(_search jsonb, _name text, _metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    named searches%ROWTYPE;
BEGIN
    named := search_query(_search, false, _metadata);
    UPDATE searches
    SET
        name = _name,
        lastused = now(),
        usecount = searches.usecount + 1
    WHERE hash = named.hash
    RETURNING * INTO named;

    IF named IS NULL THEN
        RAISE EXCEPTION 'Could not name search for input: %', _search;
    END IF;

    RETURN named;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.pgstac_hash(data text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE STRICT
AS $function$
    SELECT encode(sha256(convert_to(data, 'UTF8')), 'hex');
$function$
;

CREATE OR REPLACE FUNCTION pgstac.pgstac_hash_fragment(fragment jsonb)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
AS $function$
SELECT pgstac_hash(fragment::text);
$function$
;

CREATE OR REPLACE FUNCTION pgstac.pin_search(_name text)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    pinned_search searches%ROWTYPE;
BEGIN
    UPDATE searches
    SET
        pinned = true,
        lastused = now(),
        usecount = searches.usecount + 1
    WHERE name = _name
    RETURNING * INTO pinned_search;

    IF pinned_search IS NULL THEN
        RAISE EXCEPTION 'Named search % not found', _name;
    END IF;

    RETURN pinned_search;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.refresh_field_registry(_collection text DEFAULT NULL::text, retention_interval interval DEFAULT '90 days'::interval)
 RETURNS TABLE(collection_id text, expired_paths integer)
 LANGUAGE sql
AS $function$
    WITH deleted AS (
        DELETE FROM item_field_registry
        WHERE (_collection IS NULL OR collection = _collection)
          AND last_seen < now() - retention_interval
        RETURNING collection
    )
    SELECT collection, count(*)::int
    FROM deleted
    GROUP BY collection;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.rename_search(_old_name text, _new_name text)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    renamed searches%ROWTYPE;
BEGIN
    -- Serialize rename-pair operations to avoid deadlocks on concurrent name swaps.
    PERFORM pg_advisory_xact_lock(
        hashtext(
            least(_old_name, _new_name)
            || '|'
            || greatest(_old_name, _new_name)
        )
    );

    UPDATE searches
    SET
        name = _new_name,
        lastused = now(),
        usecount = searches.usecount + 1
    WHERE name = _old_name
    RETURNING * INTO renamed;

    IF renamed IS NULL THEN
        RAISE EXCEPTION 'Named search % not found', _old_name;
    END IF;

    RETURN renamed;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search_gc_retention_interval(conf jsonb DEFAULT NULL::jsonb)
 RETURNS interval
 LANGUAGE sql
AS $function$
    SELECT pgstac.get_setting('search_gc_retention_interval', conf)::interval;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search_hash(_search jsonb, _metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS text
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
    SELECT search_hash_from_where(
        stac_search_to_where(_search),
        _metadata
    );
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search_hash_from_where(_where text, _metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
AS $function$
    SELECT pgstac_hash(
        format(
            '%s|%s',
            _where,
            coalesce(_metadata, '{}'::jsonb)::text
        )
    );
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search_rows(_where text DEFAULT 'TRUE'::text, _orderby text DEFAULT 'datetime DESC, id DESC'::text, _limit integer DEFAULT 10)
 RETURNS SETOF items
 LANGUAGE plpgsql
 SET search_path TO 'pgstac', 'public'
AS $function$
DECLARE
    base_query text;
    query text;
    sdate timestamptz;
    edate timestamptz;
    n int;
    records_left int := _limit;
    timer timestamptz := clock_timestamp();
    full_timer timestamptz := clock_timestamp();
BEGIN
IF _where IS NULL OR trim(_where) = '' THEN
    _where = ' TRUE ';
END IF;
RAISE NOTICE 'Getting chunks for % %', _where, _orderby;

base_query := $q$
    SELECT * FROM items
    WHERE
    datetime >= %L AND datetime < %L
    AND (%s)
    ORDER BY %s
    LIMIT %L
$q$;

IF _orderby ILIKE 'datetime d%' THEN
    FOR sdate, edate IN SELECT * FROM chunker(_where) ORDER BY 1 DESC LOOP
        RAISE NOTICE 'Running Query for % to %. %', sdate, edate, age_ms(full_timer);
        query := format(
            base_query,
            sdate,
            edate,
            _where,
            _orderby,
            records_left
        );
        RAISE DEBUG 'QUERY: %', query;
        timer := clock_timestamp();
        RETURN QUERY EXECUTE query;

        GET DIAGNOSTICS n = ROW_COUNT;
        records_left := records_left - n;
        RAISE NOTICE 'Returned %/% Rows From % to %. % to go. Time: %ms', n, _limit, sdate, edate, records_left, age_ms(timer);
        timer := clock_timestamp();
        IF records_left <= 0 THEN
            RAISE NOTICE 'SEARCH_ROWS TOOK %ms', age_ms(full_timer);
            RETURN;
        END IF;
    END LOOP;
ELSIF _orderby ILIKE 'datetime a%' THEN
    FOR sdate, edate IN SELECT * FROM chunker(_where) ORDER BY 1 ASC LOOP
        RAISE NOTICE 'Running Query for % to %. %', sdate, edate, age_ms(full_timer);
        query := format(
            base_query,
            sdate,
            edate,
            _where,
            _orderby,
            records_left
        );
        RAISE DEBUG 'QUERY: %', query;
        timer := clock_timestamp();
        RETURN QUERY EXECUTE query;

        GET DIAGNOSTICS n = ROW_COUNT;
        records_left := records_left - n;
        RAISE NOTICE 'Returned %/% Rows From % to %. % to go. Time: %ms', n, _limit, sdate, edate, records_left, age_ms(timer);
        timer := clock_timestamp();
        IF records_left <= 0 THEN
            RAISE NOTICE 'SEARCH_ROWS TOOK %ms', age_ms(full_timer);
            RETURN;
        END IF;
    END LOOP;
ELSE
    query := format($q$
        SELECT * FROM items
        WHERE %s
        ORDER BY %s
        LIMIT %L
    $q$, _where, _orderby, _limit
    );
    RAISE DEBUG 'QUERY: %', query;
    timer := clock_timestamp();
    RETURN QUERY EXECUTE query;
    RAISE NOTICE 'FULL QUERY TOOK %ms', age_ms(timer);
END IF;
RAISE NOTICE 'SEARCH_ROWS TOOK %ms', age_ms(full_timer);
RETURN;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.unname_search(_name text)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    unnamed searches%ROWTYPE;
BEGIN
    UPDATE searches
    SET
        name = NULL,
        pinned = false,
        lastused = now(),
        usecount = searches.usecount + 1
    WHERE name = _name
    RETURNING * INTO unnamed;

    IF unnamed IS NULL THEN
        RAISE EXCEPTION 'Named search % not found', _name;
    END IF;

    RETURN unnamed;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.unpin_search(_name text)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    unpinned_search searches%ROWTYPE;
BEGIN
    UPDATE searches
    SET
        pinned = false,
        lastused = now(),
        usecount = searches.usecount + 1
    WHERE name = _name
    RETURNING * INTO unpinned_search;

    IF unpinned_search IS NULL THEN
        RAISE EXCEPTION 'Named search % not found', _name;
    END IF;

    RETURN unpinned_search;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.update_field_registry_from_items(_collection text)
 RETURNS TABLE(registered_paths integer, rows_processed integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    est_rows bigint;
    nrows    int;
    npaths   int;
BEGIN
    -- Sum reltuples across all partitions for this collection.
    -- reltuples can be -1 (never analyzed); treat negative values as zero.
    SELECT COALESCE(sum(GREATEST(c.reltuples::bigint, 0)), 0) INTO est_rows
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'pgstac'
      AND c.relkind = 'r'
      AND c.relname LIKE '_items_%'
      AND c.relname LIKE '%' || regexp_replace(_collection, '[^a-zA-Z0-9_-]', '', 'g') || '%';

    IF est_rows > 10000 THEN
        -- Large collection: use statistical sampling to avoid full seq-scan.
        WITH sampled AS (
            SELECT content FROM items TABLESAMPLE BERNOULLI(5) WHERE collection = _collection
        ),
        upserted AS (
            INSERT INTO item_field_registry (collection, path, is_leaf, value_kinds, first_seen, last_seen)
            SELECT
                _collection,
                r.path,
                bool_and(r.is_leaf)                                                       AS is_leaf,
                array_agg(DISTINCT r.value_kind) FILTER (WHERE r.value_kind IS NOT NULL)  AS value_kinds,
                now(), now()
            FROM sampled
            CROSS JOIN LATERAL jsonb_field_rows(content) AS r(path, is_leaf, value_kind)
            GROUP BY r.path
            ON CONFLICT (collection, path) DO UPDATE SET
                is_leaf     = EXCLUDED.is_leaf,
                value_kinds = (
                    SELECT array_agg(DISTINCT v)
                    FROM unnest(item_field_registry.value_kinds || EXCLUDED.value_kinds) t(v)
                ),
                last_seen   = now()
            RETURNING 1
        )
        SELECT
            (SELECT count(*)::int FROM upserted),
            (SELECT count(*)::int FROM sampled)
        INTO npaths, nrows;
    ELSE
        -- Small collection: process up to 1000 rows to avoid BERNOULLI returning 0 rows.
        WITH sampled AS (
            SELECT content FROM items WHERE collection = _collection LIMIT 1000
        ),
        upserted AS (
            INSERT INTO item_field_registry (collection, path, is_leaf, value_kinds, first_seen, last_seen)
            SELECT
                _collection,
                r.path,
                bool_and(r.is_leaf)                                                       AS is_leaf,
                array_agg(DISTINCT r.value_kind) FILTER (WHERE r.value_kind IS NOT NULL)  AS value_kinds,
                now(), now()
            FROM sampled
            CROSS JOIN LATERAL jsonb_field_rows(content) AS r(path, is_leaf, value_kind)
            GROUP BY r.path
            ON CONFLICT (collection, path) DO UPDATE SET
                is_leaf     = EXCLUDED.is_leaf,
                value_kinds = (
                    SELECT array_agg(DISTINCT v)
                    FROM unnest(item_field_registry.value_kinds || EXCLUDED.value_kinds) t(v)
                ),
                last_seen   = now()
            RETURNING 1
        )
        SELECT
            (SELECT count(*)::int FROM upserted),
            (SELECT count(*)::int FROM sampled)
        INTO npaths, nrows;
    END IF;

    RETURN QUERY SELECT npaths, nrows;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.update_field_registry_from_sample(_collection text, item_contents jsonb[])
 RETURNS void
 LANGUAGE sql
AS $function$
    INSERT INTO item_field_registry (collection, path, is_leaf, value_kinds, first_seen, last_seen)
    SELECT
        _collection,
        r.path,
        bool_and(r.is_leaf)                                                       AS is_leaf,
        array_agg(DISTINCT r.value_kind) FILTER (WHERE r.value_kind IS NOT NULL)  AS value_kinds,
        now(),
        now()
    FROM unnest(item_contents) AS item(content)
    CROSS JOIN LATERAL jsonb_field_rows(item.content) AS r(path, is_leaf, value_kind)
    GROUP BY r.path
    ON CONFLICT (collection, path) DO UPDATE SET
        is_leaf     = EXCLUDED.is_leaf,
        value_kinds = (
            SELECT array_agg(DISTINCT v)
            FROM unnest(item_field_registry.value_kinds || EXCLUDED.value_kinds) t(v)
        ),
        last_seen   = now()
    ;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.where_stats(inhash text, inwhere text, updatestats boolean DEFAULT false, conf jsonb DEFAULT NULL::jsonb)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    t timestamptz;
    i interval;
    explain_json jsonb;
    sw searches%ROWTYPE;
    sw_statslastupdated timestamptz;
    sw_estimated_count bigint;
    sw_estimated_cost float;
    _context text := lower(context(conf));
    _stats_ttl interval := context_stats_ttl(conf);
    _estimated_cost_threshold float := context_estimated_cost(conf);
    _estimated_count_threshold int := context_estimated_count(conf);
    ro bool := pgstac.readonly(conf);
BEGIN
    -- If updatestats is true then set ttl to 0
    IF updatestats THEN
        RAISE DEBUG 'Updatestats set to TRUE, setting TTL to 0';
        _stats_ttl := '0'::interval;
    END IF;

    -- If we don't need to calculate context, just return
    IF _context = 'off' THEN
        RETURN sw;
    END IF;

    -- Read current stats state without holding row locks during expensive
    -- estimate/count operations.
    SELECT * INTO sw FROM searches WHERE hash = inhash;

    IF sw IS NULL THEN
        -- In read-only mode, searches may not be persisted. Continue with
        -- non-persistent estimate/count calculation so context can still be
        -- returned to callers.
        sw.hash := inhash;
        sw._where := inwhere;
        sw_statslastupdated := NULL;
    ELSE
        sw_statslastupdated := sw.statslastupdated;
    END IF;

    -- If there is a cached row, figure out if we need to update
    IF
        sw IS NOT NULL
        AND sw.statslastupdated IS NOT NULL
        AND sw.context_count IS NOT NULL
        AND now() - sw.statslastupdated <= _stats_ttl
    THEN
        -- We have a cached row with data that is within our ttl.
        RAISE DEBUG 'Stats present in table and lastupdated within ttl: %', sw;
        RAISE DEBUG 'Returning cached counts. %', sw;
        RETURN sw;
    END IF;

    -- Calculate estimated cost and rows
    -- Use explain to get estimated count/cost
    RAISE DEBUG 'Calculating estimated stats';
    t := clock_timestamp();
    EXECUTE format('EXPLAIN (format json) SELECT 1 FROM items WHERE %s', inwhere)
        INTO explain_json;
    RAISE DEBUG 'Time for just the explain: %', clock_timestamp() - t;
    i := clock_timestamp() - t;

    sw_estimated_count := (explain_json->0->'Plan'->>'Plan Rows')::bigint;
    sw_estimated_cost := (explain_json->0->'Plan'->>'Total Cost')::float;

    RAISE DEBUG 'ESTIMATED_COUNT: %, THRESHOLD %', sw_estimated_count, _estimated_count_threshold;
    RAISE DEBUG 'ESTIMATED_COST: %, THRESHOLD %', sw_estimated_cost, _estimated_cost_threshold;

    -- If context is set to auto and the costs are within the threshold return the estimated costs
    IF
        _context = 'auto'
        AND sw_estimated_count >= _estimated_count_threshold
        AND sw_estimated_cost >= _estimated_cost_threshold
    THEN
        sw.context_count := sw_estimated_count;
        IF NOT ro THEN
            UPDATE searches SET
                statslastupdated = now(),
                context_count = sw.context_count
            WHERE
                hash = inhash
                AND statslastupdated IS NOT DISTINCT FROM sw_statslastupdated
            RETURNING * INTO sw;

            IF sw IS NULL THEN
                SELECT * INTO sw FROM searches WHERE hash = inhash;
            END IF;
        END IF;
        RAISE DEBUG 'Estimates are within thresholds, returning estimates. %', sw;
        RETURN sw;
    END IF;

    -- Calculate Actual Count
    t := clock_timestamp();
    RAISE NOTICE 'Calculating actual count...';
    EXECUTE format(
        'SELECT count(*) FROM items WHERE %s',
        inwhere
    ) INTO sw.context_count;
    i := clock_timestamp() - t;
    RAISE NOTICE 'Actual Count: % -- %', sw.context_count, i;

    IF NOT ro THEN
        UPDATE searches SET
            statslastupdated = now(),
            context_count = sw.context_count
        WHERE
            hash = inhash
            AND statslastupdated IS NOT DISTINCT FROM sw_statslastupdated
        RETURNING * INTO sw;

        IF sw IS NULL THEN
            SELECT * INTO sw FROM searches WHERE hash = inhash;
        END IF;
    END IF;
    RAISE DEBUG 'Returning with actual count. %', sw;
    RETURN sw;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.content_dehydrate(content jsonb)
 RETURNS items
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
    out items;
    props jsonb;
    base_item jsonb;
BEGIN
    out.id := content->>'id';
    out.geometry := stac_geom(content);
    out.collection := content->>'collection';
    out.datetime := stac_datetime(content);
    out.end_datetime := stac_end_datetime(content);
    out.pgstac_updated_at := now();
    out.content_hash := encode(sha256(content::text::bytea), 'hex');

    base_item := collection_base_item(content->>'collection');
    props := content->'properties';

    -- Split columns: dedicated storage for standard top-level STAC fields.
    -- These enable index-only scans on promoted queryables and avoid JSONB parse
    -- on the hot SELECT path once the legacy content column is retired.
    out.bbox       := content->'bbox';
    out.links      := COALESCE(content->'links', '[]'::jsonb);
    out.assets     := COALESCE(content->'assets', '{}'::jsonb);
    out.properties := COALESCE(props, '{}'::jsonb);
    -- extra: non-standard top-level fields not in id/geometry/collection/type/bbox/links/assets/properties
    out.extra      := content - '{id,geometry,collection,type,bbox,links,assets,properties}'::text[];

    -- Promoted queryable columns: direct float8 storage avoids JSONB parse on range queries.
    out.eo_cloud_cover    := (props->>'eo:cloud_cover')::float8;
    out.eo_snow_cover     := (props->>'eo:snow_cover')::float8;
    out.gsd               := (props->>'gsd')::float8;
    out.view_off_nadir    := (props->>'view:off_nadir')::float8;
    out.view_sun_azimuth  := (props->>'view:sun_azimuth')::float8;
    out.view_sun_elevation := (props->>'view:sun_elevation')::float8;

    -- Legacy content column: kept for backwards compatibility with clients that
    -- read items.content directly. Contains all fields except id/geometry/collection/type,
    -- with base_item fields stripped out for dedup storage.
    -- NOTE: content_hash above hashes the raw incoming JSONB (pre-strip), which is
    -- intentional for change detection; it differs from the hash produced by
    -- items_touch_triggerfunc (which hashes the hydrated form on UPDATE).
    out.content := strip_jsonb(
        content - '{id,geometry,collection,type}'::text[],
        base_item
    ) - '{id,geometry,collection,type}'::text[];

    out.private := null;
    RETURN out;
END;
$function$
;

CREATE TRIGGER items_before_update_trigger BEFORE UPDATE ON pgstac.items FOR EACH ROW WHEN (((old.content IS DISTINCT FROM new.content) OR (old.bbox IS DISTINCT FROM new.bbox) OR (old.links IS DISTINCT FROM new.links) OR (old.assets IS DISTINCT FROM new.assets) OR (old.properties IS DISTINCT FROM new.properties) OR (old.extra IS DISTINCT FROM new.extra))) EXECUTE FUNCTION items_touch_triggerfunc();

CREATE TRIGGER items_delete_log_after_delete_trigger AFTER DELETE ON pgstac.items REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION items_delete_log_trigger();

CREATE OR REPLACE FUNCTION pgstac.content_dehydrate(content jsonb)
 RETURNS items
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
    out items;
    props jsonb;
    base_item jsonb;
BEGIN
    out.id := content->>'id';
    out.geometry := stac_geom(content);
    out.collection := content->>'collection';
    out.datetime := stac_datetime(content);
    out.end_datetime := stac_end_datetime(content);
    out.pgstac_updated_at := now();
    out.content_hash := encode(sha256(content::text::bytea), 'hex');

    base_item := collection_base_item(content->>'collection');
    props := content->'properties';

    -- Split columns: dedicated storage for standard top-level STAC fields.
    -- These enable index-only scans on promoted queryables and avoid JSONB parse
    -- on the hot SELECT path once the legacy content column is retired.
    out.bbox       := content->'bbox';
    out.links      := COALESCE(content->'links', '[]'::jsonb);
    out.assets     := COALESCE(content->'assets', '{}'::jsonb);
    out.properties := COALESCE(props, '{}'::jsonb);
    -- extra: non-standard top-level fields not in id/geometry/collection/type/bbox/links/assets/properties
    out.extra      := content - '{id,geometry,collection,type,bbox,links,assets,properties}'::text[];

    -- Promoted queryable columns: direct float8 storage avoids JSONB parse on range queries.
    out.eo_cloud_cover    := (props->>'eo:cloud_cover')::float8;
    out.eo_snow_cover     := (props->>'eo:snow_cover')::float8;
    out.gsd               := (props->>'gsd')::float8;
    out.view_off_nadir    := (props->>'view:off_nadir')::float8;
    out.view_sun_azimuth  := (props->>'view:sun_azimuth')::float8;
    out.view_sun_elevation := (props->>'view:sun_elevation')::float8;

    -- Legacy content column: kept for backwards compatibility with clients that
    -- read items.content directly. Contains all fields except id/geometry/collection/type,
    -- with base_item fields stripped out for dedup storage.
    -- NOTE: content_hash above hashes the raw incoming JSONB (pre-strip), which is
    -- intentional for change detection; it differs from the hash produced by
    -- items_touch_triggerfunc (which hashes the hydrated form on UPDATE).
    out.content := strip_jsonb(
        content - '{id,geometry,collection,type}'::text[],
        base_item
    ) - '{id,geometry,collection,type}'::text[];

    out.private := null;
    RETURN out;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.content_hydrate(_item items, _collection collections, fields jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE PARALLEL SAFE
AS $function$
DECLARE
    geom jsonb;
    output jsonb;
    content jsonb;
BEGIN
    IF include_field('geometry', fields) THEN
        geom := ST_ASGeoJson(_item.geometry, 20)::jsonb;
    END IF;

    IF _item.fragment_id IS NOT NULL THEN
        -- Preferred path: reconstruct item from split columns.
        -- fragment_id IS NOT NULL is the canonical indicator that split columns
        -- are populated; checking a nullable bigint is cheaper than a JSONB equality.
        content := jsonb_build_object(
            'id',         _item.id,
            'geometry',   geom,
            'collection', _item.collection,
            'type',       'Feature'
        );
        IF _item.bbox IS NOT NULL THEN
            content := content || jsonb_build_object('bbox', _item.bbox);
        END IF;
        IF _item.links IS NOT NULL THEN
            content := content || jsonb_build_object('links', _item.links);
        END IF;
        IF _item.assets IS NOT NULL THEN
            content := content || jsonb_build_object('assets', _item.assets);
        END IF;
        IF _item.properties IS NOT NULL THEN
            content := content || jsonb_build_object('properties', _item.properties);
        END IF;
        IF _item.extra IS NOT NULL THEN
            content := content || _item.extra;
        END IF;
    ELSE
        -- Legacy fallback: reconstruct from the content column (pre-v0.10 rows).
        content := jsonb_build_object(
            'id',         _item.id,
            'geometry',   geom,
            'collection', _item.collection,
            'type',       'Feature'
        ) || _item.content;
    END IF;

    output := content_hydrate(content, _collection.base_item, fields);
    RETURN output;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.items_staging_triggerfunc()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    p record;
    _partitions text[];
    part text;
    ts timestamptz := clock_timestamp();
    nrows int;
BEGIN
    RAISE NOTICE 'Creating Partitions. %', clock_timestamp() - ts;

    FOR part IN WITH t AS (
        SELECT
            n.content->>'collection' as collection,
            stac_daterange(n.content->'properties') as dtr,
            partition_trunc
        FROM newdata n JOIN collections ON (n.content->>'collection'=collections.id)
    ), p AS (
        SELECT
            collection,
            COALESCE(date_trunc(partition_trunc::text, lower(dtr)),'-infinity') as d,
            tstzrange(min(lower(dtr)),max(lower(dtr)),'[]') as dtrange,
            tstzrange(min(upper(dtr)),max(upper(dtr)),'[]') as edtrange
        FROM t
        GROUP BY 1,2
    ) SELECT check_partition(collection, dtrange, edtrange) FROM p LOOP
        RAISE NOTICE 'Partition %', part;
    END LOOP;

    RAISE NOTICE 'Creating temp table with data to be added. %', clock_timestamp() - ts;
    DROP TABLE IF EXISTS tmpdata;
    CREATE TEMP TABLE tmpdata ON COMMIT DROP AS
    SELECT
        (content_dehydrate(content)).*
    FROM newdata;
    GET DIAGNOSTICS nrows = ROW_COUNT;
    RAISE NOTICE 'Added % rows to tmpdata. %', nrows, clock_timestamp() - ts;

    -- Batch fragment dedup: insert all unique fragments in one statement rather than
    -- calling get_or_create_fragment() per row (which is O(N) round-trips).
    -- pgstac_hash_fragment(content) is computed twice (once for insert, once for the
    -- join update) but both calls are IMMUTABLE so the planner can CSE them; the net
    -- cost is far lower than N individual PL/pgSQL function round-trips.
    -- Concurrent inserts of identical fragments are safe: ON CONFLICT DO NOTHING means
    -- both sides succeed with the same row; the join below finds it for either winner.
    RAISE NOTICE 'Batch inserting fragments. %', clock_timestamp() - ts;
    INSERT INTO item_fragments (collection, hash, content)
    SELECT DISTINCT ON (collection, pgstac_hash_fragment(content))
        collection,
        pgstac_hash_fragment(content) AS hash,
        content
    FROM tmpdata
    WHERE content IS NOT NULL AND content != '{}'::jsonb
    ON CONFLICT (collection, hash) DO NOTHING;

    RAISE NOTICE 'Assigning fragment_id. %', clock_timestamp() - ts;
    UPDATE tmpdata t
    SET fragment_id = f.id
    FROM item_fragments f
    WHERE f.collection = t.collection
      AND f.hash = pgstac_hash_fragment(t.content)
      AND t.content IS NOT NULL AND t.content != '{}'::jsonb;

    -- Queue registry sampling per collection (async via run_or_queue so it does not
    -- block the ingest transaction).  One queued call per distinct collection in the batch.
    PERFORM run_or_queue(format('SELECT update_field_registry_from_items(%L);', c))
    FROM (SELECT DISTINCT collection FROM tmpdata) AS cte(c);

    RAISE NOTICE 'Doing the insert. %', clock_timestamp() - ts;
    IF TG_TABLE_NAME = 'items_staging' THEN
        INSERT INTO items
        SELECT * FROM tmpdata;
        GET DIAGNOSTICS nrows = ROW_COUNT;
        RAISE NOTICE 'Inserted % rows to items. %', nrows, clock_timestamp() - ts;
    ELSIF TG_TABLE_NAME = 'items_staging_ignore' THEN
        INSERT INTO items
        SELECT * FROM tmpdata
        ON CONFLICT DO NOTHING;
        GET DIAGNOSTICS nrows = ROW_COUNT;
        RAISE NOTICE 'Inserted % rows to items. %', nrows, clock_timestamp() - ts;
    ELSIF TG_TABLE_NAME = 'items_staging_upsert' THEN
        DELETE FROM items i USING tmpdata s
            WHERE
                i.id = s.id
                AND i.collection = s.collection
                AND i IS DISTINCT FROM s
        ;
        GET DIAGNOSTICS nrows = ROW_COUNT;
        RAISE NOTICE 'Deleted % rows from items. %', nrows, clock_timestamp() - ts;
        INSERT INTO items AS t
        SELECT * FROM tmpdata
        ON CONFLICT DO NOTHING;
        GET DIAGNOSTICS nrows = ROW_COUNT;
        RAISE NOTICE 'Inserted % rows to items. %', nrows, clock_timestamp() - ts;
    END IF;

    RAISE NOTICE 'Deleting data from staging table. %', clock_timestamp() - ts;
    -- Use TG_TABLE_NAME so the correct staging table is cleared.
    -- The previous hard-coded 'DELETE FROM items_staging' was a bug that left
    -- items_staging_ignore and items_staging_upsert un-cleared after processing.
    EXECUTE format('DELETE FROM %I', TG_TABLE_NAME);
    RAISE NOTICE 'Done. %', clock_timestamp() - ts;

    RETURN NULL;

END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search(_search jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
    searches searches%ROWTYPE;
    _where text;
    orderby text;
    search_where searches%ROWTYPE;
    total_count bigint;
    token record;
    token_prev boolean;
    token_item items%ROWTYPE;
    token_where text;
    full_where text;
    init_ts timestamptz := clock_timestamp();
    timer timestamptz := clock_timestamp();
    hydrate bool := NOT (_search->'conf'->>'nohydrate' IS NOT NULL AND (_search->'conf'->>'nohydrate')::boolean = true);
    prev text;
    next text;
    collection jsonb;
    out_records jsonb;
    out_len int;
    _limit int := coalesce((_search->>'limit')::int, 10);
    _querylimit int;
    _fields jsonb := coalesce(_search->'fields', '{}'::jsonb);
    has_prev boolean := FALSE;
    has_next boolean := FALSE;
    links jsonb := '[]'::jsonb;
    base_url text:= concat(rtrim(base_url(_search->'conf'),'/'));
BEGIN
    searches := search_query(_search);
    _where := searches._where;
    orderby := searches.orderby;
    search_where := where_stats(searches.hash, _where, false, _search->'conf');
    total_count := search_where.context_count;
    RAISE NOTICE 'SEARCH:TOKEN: %', _search->>'token';
    token := get_token_record(_search->>'token');
    RAISE NOTICE '***TOKEN: %', token;
    _querylimit := _limit + 1;
    IF token IS NOT NULL THEN
        token_prev := token.prev;
        token_item := token.item;
        token_where := get_token_filter(_search->'sortby', token_item, token_prev, FALSE);
        RAISE DEBUG 'TOKEN_WHERE: % (%ms from search start)', token_where, age_ms(timer);
        IF token_prev THEN -- if we are using a prev token, we know has_next is true
            RAISE DEBUG 'There is a previous token, so automatically setting has_next to true';
            has_next := TRUE;
            orderby := sort_sqlorderby(_search, TRUE);
        ELSE
            RAISE DEBUG 'There is a next token, so automatically setting has_prev to true';
            has_prev := TRUE;

        END IF;
    ELSE -- if there was no token, we know there is no prev
        RAISE DEBUG 'There is no token, so we know there is no prev. setting has_prev to false';
        has_prev := FALSE;
    END IF;

    full_where := concat_ws(' AND ', _where, token_where);
    RAISE NOTICE 'FULL WHERE CLAUSE: %', full_where;
    RAISE NOTICE 'Time to get counts and build query %', age_ms(timer);
    timer := clock_timestamp();

    IF hydrate THEN
        RAISE NOTICE 'Getting hydrated data.';
    ELSE
        RAISE NOTICE 'Getting non-hydrated data.';
    END IF;
    RAISE NOTICE 'CACHE SET TO %', get_setting_bool('format_cache');
    RAISE NOTICE 'Time to set hydration/formatting %', age_ms(timer);
    timer := clock_timestamp();
    SELECT jsonb_agg(format_item(i, _fields, hydrate)) INTO out_records
    FROM search_rows(
        full_where,
        orderby,
        _querylimit
    ) as i;

    RAISE NOTICE 'Time to fetch rows %', age_ms(timer);
    timer := clock_timestamp();


    IF token_prev THEN
        out_records := flip_jsonb_array(out_records);
    END IF;

    RAISE NOTICE 'Query returned % records.', jsonb_array_length(out_records);
    RAISE DEBUG 'TOKEN:   % %', token_item.id, token_item.collection;
    RAISE DEBUG 'RECORD_1: % %', out_records->0->>'id', out_records->0->>'collection';
    RAISE DEBUG 'RECORD-1: % %', out_records->-1->>'id', out_records->-1->>'collection';

    -- REMOVE records that were from our token
    IF out_records->0->>'id' = token_item.id AND out_records->0->>'collection' = token_item.collection THEN
        out_records := out_records - 0;
    ELSIF out_records->-1->>'id' = token_item.id AND out_records->-1->>'collection' = token_item.collection THEN
        out_records := out_records - -1;
    END IF;

    out_len := jsonb_array_length(out_records);

    IF out_len = _limit + 1 THEN
        IF token_prev THEN
            has_prev := TRUE;
            out_records := out_records - 0;
        ELSE
            has_next := TRUE;
            out_records := out_records - -1;
        END IF;
    END IF;


    links := links || jsonb_build_object(
        'rel', 'root',
        'type', 'application/json',
        'href', base_url
    ) || jsonb_build_object(
        'rel', 'self',
        'type', 'application/json',
        'href', concat(base_url, '/search')
    );

    IF has_next THEN
        next := concat(out_records->-1->>'collection', ':', out_records->-1->>'id');
        RAISE NOTICE 'HAS NEXT | %', next;
        links := links || jsonb_build_object(
            'rel', 'next',
            'type', 'application/geo+json',
            'method', 'GET',
            'href', concat(base_url, '/search?token=next:', next)
        );
    END IF;

    IF has_prev THEN
        prev := concat(out_records->0->>'collection', ':', out_records->0->>'id');
        RAISE NOTICE 'HAS PREV | %', prev;
        links := links || jsonb_build_object(
            'rel', 'prev',
            'type', 'application/geo+json',
            'method', 'GET',
            'href', concat(base_url, '/search?token=prev:', prev)
        );
    END IF;

    RAISE NOTICE 'Time to get prev/next %', age_ms(timer);
    timer := clock_timestamp();


    collection := jsonb_build_object(
        'type', 'FeatureCollection',
        'features', coalesce(out_records, '[]'::jsonb),
        'links', links
    );



    IF context(_search->'conf') != 'off' THEN
        collection := collection || jsonb_strip_nulls(jsonb_build_object(
            'numberMatched', total_count,
            'numberReturned', coalesce(jsonb_array_length(out_records), 0)
        ));
    ELSE
        collection := collection || jsonb_strip_nulls(jsonb_build_object(
            'numberReturned', coalesce(jsonb_array_length(out_records), 0)
        ));
    END IF;

    IF get_setting_bool('timing', _search->'conf') THEN
        collection = collection || jsonb_build_object('timing', age_ms(init_ts));
    END IF;

    RAISE NOTICE 'Time to build final json %', age_ms(timer);
    timer := clock_timestamp();

    RAISE NOTICE 'Total Time: %', age_ms(current_timestamp);
    RAISE NOTICE 'RETURNING % records. NEXT: %. PREV: %', collection->>'numberReturned', collection->>'next', collection->>'prev';
    RETURN collection;
END;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search_fromhash(_hash text)
 RETURNS searches
 LANGUAGE sql
 STRICT
AS $function$
    SELECT * FROM searches WHERE hash = _hash LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION pgstac.search_query(_search jsonb DEFAULT '{}'::jsonb, updatestats boolean DEFAULT false, _metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS searches
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    search searches%ROWTYPE;
    cached_search searches%ROWTYPE;
    search_where searches%ROWTYPE;
    ro boolean := pgstac.readonly();
BEGIN
    RAISE NOTICE 'SEARCH: %', _search;
    -- Calculate hash, where clause, and order by statement
    search.search := _search;
    search.metadata := _metadata;
    search._where := stac_search_to_where(_search);
    search.hash := search_hash_from_where(search._where, search.metadata);
    search.orderby := sort_sqlorderby(_search);
    search.lastused := now();
    search.usecount := 1;

    -- If we are in read only mode, directly return search
    IF ro THEN
        RETURN search;
    END IF;

    -- Cache bookkeeping is best-effort and non-blocking. We always return
    -- canonical hash + where, even if cache touch cannot be acquired quickly.
    UPDATE searches
    SET
        lastused = now(),
        usecount = searches.usecount + 1
    WHERE ctid = (
        SELECT ctid
        FROM searches
        WHERE hash = search.hash
        FOR UPDATE SKIP LOCKED
        LIMIT 1
    )
    RETURNING * INTO cached_search;

    IF cached_search IS NULL THEN
        IF pg_try_advisory_xact_lock(hashtext(search.hash)) THEN
            INSERT INTO searches (hash, search, _where, orderby, lastused, usecount, metadata)
                VALUES (search.hash, search.search, search._where, search.orderby, now(), 1, search.metadata)
                ON CONFLICT (hash) DO UPDATE SET
                    lastused = EXCLUDED.lastused,
                    usecount = searches.usecount + 1
                RETURNING * INTO cached_search;
        END IF;

        IF cached_search IS NULL THEN
            SELECT * INTO cached_search FROM searches WHERE hash = search.hash;
        END IF;
    END IF;

    IF cached_search IS NOT NULL THEN
        cached_search._where = search._where;
        cached_search.orderby = search.orderby;
        IF updatestats THEN
            search_where := where_stats(
                cached_search.hash,
                cached_search._where,
                true,
                _search->'conf'
            );
            cached_search.context_count := search_where.context_count;
            cached_search.statslastupdated := search_where.statslastupdated;
        END IF;
        RETURN cached_search;
    END IF;

    IF updatestats THEN
        search_where := where_stats(
            search.hash,
            search._where,
            true,
            _search->'conf'
        );
        search.context_count := search_where.context_count;
        search.statslastupdated := search_where.statslastupdated;
    END IF;

    RETURN search;

END;
$function$
;
DO $$
  BEGIN
    INSERT INTO queryables (name, definition, property_wrapper, property_index_type) VALUES
    ('id', '{"title": "Item ID","description": "Item identifier","$ref": "https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json#/definitions/core/allOf/2/properties/id"}', null, null);
  EXCEPTION WHEN unique_violation THEN
    RAISE NOTICE '%', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;

DO $$
  BEGIN
    INSERT INTO queryables (name, definition, property_wrapper, property_index_type) VALUES
    ('geometry', '{"title": "Item Geometry","description": "Item Geometry","$ref": "https://geojson.org/schema/Feature.json"}', null, null);
  EXCEPTION WHEN unique_violation THEN
    RAISE NOTICE '%', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;

DO $$
  BEGIN
    INSERT INTO queryables (name, definition, property_wrapper, property_index_type) VALUES
    ('datetime','{"description": "Datetime","type": "string","title": "Acquired","format": "date-time","pattern": "(\\+00:00|Z)$"}', null, null);
  EXCEPTION WHEN unique_violation THEN
    RAISE NOTICE '%', SQLERRM USING ERRCODE = SQLSTATE;
  END
$$;

DELETE FROM queryables a USING queryables b
  WHERE a.name = b.name AND a.collection_ids IS NOT DISTINCT FROM b.collection_ids AND a.id > b.id;


INSERT INTO pgstac_settings (name, value) VALUES
  ('context', 'off'),
  ('context_estimated_count', '100000'),
  ('context_estimated_cost', '100000'),
  ('context_stats_ttl', '1 day'),
  ('search_gc_retention_interval', '7 days'),
  ('default_filter_lang', 'cql2-json'),
  ('additional_properties', 'true'),
  ('use_queue', 'false'),
  ('queue_timeout', '10 minutes'),
  ('update_collection_extent', 'false'),
  ('format_cache', 'false'),
  ('readonly', 'false')
ON CONFLICT DO NOTHING
;


INSERT INTO cql2_ops (op, template, types) VALUES
    ('eq', '%s = %s', NULL),
    ('neq', '%s != %s', NULL),
    ('ne', '%s != %s', NULL),
    ('!=', '%s != %s', NULL),
    ('<>', '%s != %s', NULL),
    ('lt', '%s < %s', NULL),
    ('lte', '%s <= %s', NULL),
    ('gt', '%s > %s', NULL),
    ('gte', '%s >= %s', NULL),
    ('le', '%s <= %s', NULL),
    ('ge', '%s >= %s', NULL),
    ('=', '%s = %s', NULL),
    ('<', '%s < %s', NULL),
    ('<=', '%s <= %s', NULL),
    ('>', '%s > %s', NULL),
    ('>=', '%s >= %s', NULL),
    ('like', '%s LIKE %s', NULL),
    ('ilike', '%s ILIKE %s', NULL),
    ('+', '%s + %s', NULL),
    ('-', '%s - %s', NULL),
    ('*', '%s * %s', NULL),
    ('/', '%s / %s', NULL),
    ('not', 'NOT (%s)', NULL),
    ('between', '%s BETWEEN %s AND %s', NULL),
    ('isnull', '%s IS NULL', NULL),
    ('upper', 'upper(%s)', NULL),
    ('lower', 'lower(%s)', NULL),
    ('casei', 'upper(%s)', NULL),
    ('accenti', 'unaccent(%s)', NULL)
ON CONFLICT (op) DO UPDATE
    SET
        template = EXCLUDED.template
;


ALTER FUNCTION to_text COST 5000;
ALTER FUNCTION to_float COST 5000;
ALTER FUNCTION to_int COST 5000;
ALTER FUNCTION to_tstz COST 5000;
ALTER FUNCTION to_text_array COST 5000;

ALTER FUNCTION update_partition_stats SECURITY DEFINER;
ALTER FUNCTION partition_after_triggerfunc SECURITY DEFINER;
ALTER FUNCTION drop_table_constraints SECURITY DEFINER;
ALTER FUNCTION create_table_constraints SECURITY DEFINER;
ALTER FUNCTION check_partition SECURITY DEFINER;
ALTER FUNCTION repartition SECURITY DEFINER;
ALTER FUNCTION where_stats(text, text, boolean, jsonb) SECURITY DEFINER;
ALTER FUNCTION search_query SECURITY DEFINER;
ALTER FUNCTION name_search SECURITY DEFINER;
ALTER FUNCTION rename_search SECURITY DEFINER;
ALTER FUNCTION unname_search SECURITY DEFINER;
ALTER FUNCTION pin_search SECURITY DEFINER;
ALTER FUNCTION unpin_search SECURITY DEFINER;
ALTER FUNCTION gc_anonymous_searches(interval, jsonb) SECURITY DEFINER;
ALTER FUNCTION gc_search_caches(interval, jsonb) SECURITY DEFINER;
ALTER FUNCTION gc_deleted_items_log_batch(interval, integer) SECURITY DEFINER;
ALTER FUNCTION gc_deleted_items_log(interval, integer) SECURITY DEFINER;
ALTER FUNCTION gc_deleted_items_log(interval) SECURITY DEFINER;
ALTER FUNCTION format_item SECURITY DEFINER;
ALTER FUNCTION maintain_index SECURITY DEFINER;

GRANT USAGE ON SCHEMA pgstac to pgstac_read;
GRANT ALL ON SCHEMA pgstac to pgstac_ingest;
GRANT ALL ON SCHEMA pgstac to pgstac_admin;

-- pgstac_read role limited to using function apis
GRANT EXECUTE ON FUNCTION search TO pgstac_read;
GRANT EXECUTE ON FUNCTION search_query TO pgstac_read;
GRANT EXECUTE ON FUNCTION item_by_id TO pgstac_read;
GRANT EXECUTE ON FUNCTION get_item TO pgstac_read;
GRANT SELECT ON ALL TABLES IN SCHEMA pgstac TO pgstac_read;


GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA pgstac to pgstac_ingest;
GRANT ALL ON ALL TABLES IN SCHEMA pgstac to pgstac_ingest;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA pgstac to pgstac_ingest;

REVOKE ALL PRIVILEGES ON PROCEDURE run_queued_queries FROM public;
GRANT ALL ON PROCEDURE run_queued_queries TO pgstac_admin;

REVOKE ALL PRIVILEGES ON FUNCTION run_queued_queries_intransaction FROM public;
GRANT ALL ON FUNCTION run_queued_queries_intransaction TO pgstac_admin;

REVOKE ALL PRIVILEGES ON PROCEDURE gc_deleted_items_log_committed(interval, integer) FROM public;
GRANT ALL ON PROCEDURE gc_deleted_items_log_committed(interval, integer) TO pgstac_admin;

RESET ROLE;

SET ROLE pgstac_ingest;
SELECT update_partition_stats_q(partition) FROM partitions_view;
SELECT set_version('unreleased');
