//! Parallel partition fan-out for the dump and the optional single
//! repeatable-read snapshot.
//!
//! True parallelism needs one Postgres connection per concurrent scan (a single
//! `tokio_postgres::Client` serializes its queries on one connection), so the
//! parallel path takes a [`ClientFactory`] that mints fresh worker connections.
//! Each worker owns its connection and pulls partition jobs from a shared queue;
//! a bounded pool of `concurrency` workers runs partitions concurrently. The
//! object_store / fs sinks accept concurrent writes; the TAR sink serializes
//! internally via its own mutex, so it is safe under fan-out too (just not
//! faster).
//!
//! `--consistent`: a coordinator connection opens one
//! `REPEATABLE READ` transaction and `pg_export_snapshot()`s it; every worker
//! `SET TRANSACTION SNAPSHOT`s onto that id, so all partitions see one
//! point-in-time view even while concurrent ingest continues. The coordinator
//! holds its transaction open for the whole dump.

use crate::{Error, Result};
use std::future::Future;
use std::pin::Pin;
use tokio_postgres::Client;

/// Mints fresh worker connections for the parallel dump.
///
/// Each call must return a brand-new connection on `search_path = pgstac,
/// public`; the caller drives it concurrently with the others.
pub trait ClientFactory: Send + Sync {
    /// Opens a new connection.
    fn connect(&self) -> Pin<Box<dyn Future<Output = Result<Client>> + Send + '_>>;
}

/// A [`ClientFactory`] backed by a DSN over `NoTls` (the CLI default).
///
/// Spawns each connection's driver task and sets the pgstac search_path before
/// handing the client back.
#[derive(Debug, Clone)]
pub struct DsnFactory {
    dsn: String,
}

impl DsnFactory {
    /// Creates a factory for the given connection string.
    pub fn new(dsn: impl Into<String>) -> Self {
        DsnFactory { dsn: dsn.into() }
    }
}

impl ClientFactory for DsnFactory {
    fn connect(&self) -> Pin<Box<dyn Future<Output = Result<Client>> + Send + '_>> {
        let dsn = self.dsn.clone();
        Box::pin(async move {
            let (client, connection) = tokio_postgres::connect(&dsn, tokio_postgres::NoTls).await?;
            // The driver task runs for the connection's lifetime; we detach it
            // (the client owns the connection's liveness for our purposes).
            let _driver = tokio::spawn(async move {
                if let Err(e) = connection.await {
                    tracing::error!("pgstac worker connection error: {e}");
                }
            });
            client
                .batch_execute("SET search_path = pgstac, public;")
                .await?;
            Ok(client)
        })
    }
}

/// A held repeatable-read snapshot for a `--consistent` dump.
///
/// Owns the coordinator connection with an open transaction; dropping it (or
/// calling [`Snapshot::finish`]) ends the transaction and releases the snapshot.
pub struct Snapshot {
    client: Client,
    id: String,
}

impl std::fmt::Debug for Snapshot {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Snapshot").field("id", &self.id).finish()
    }
}

impl Snapshot {
    /// Opens a coordinator transaction and exports its snapshot id.
    pub async fn export(factory: &dyn ClientFactory) -> Result<Snapshot> {
        let client = factory.connect().await?;
        // A read-only repeatable-read transaction pins one MVCC snapshot for the
        // whole dump. It must stay open (the snapshot is only valid while the
        // exporting transaction is alive).
        client
            .batch_execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;")
            .await?;
        let id: String = client
            .query_one("SELECT pg_export_snapshot() AS s", &[])
            .await?
            .get("s");
        Ok(Snapshot { client, id })
    }

    /// The exported snapshot id (e.g. `00000003-0000001B-1`).
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Ends the coordinator transaction, releasing the snapshot.
    pub async fn finish(self) -> Result<()> {
        self.client.batch_execute("COMMIT;").await?;
        Ok(())
    }
}

/// Prepares a freshly minted worker connection to read under a shared snapshot.
///
/// Opens a repeatable-read transaction on the worker and binds it to the
/// coordinator's exported snapshot id so the worker sees the same point in time.
pub async fn bind_worker_to_snapshot(client: &Client, snapshot_id: &str) -> Result<()> {
    client
        .batch_execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;")
        .await?;
    // The snapshot id is generated by Postgres (pg_export_snapshot); it is a
    // fixed shape (digits and dashes). Validate before inlining to be safe.
    if !snapshot_id
        .bytes()
        .all(|b| b.is_ascii_hexdigit() || b == b'-')
        || snapshot_id.is_empty()
    {
        return Err(Error::Export(format!(
            "refusing to bind to malformed snapshot id {snapshot_id:?}"
        )));
    }
    client
        .batch_execute(&format!("SET TRANSACTION SNAPSHOT '{snapshot_id}';"))
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn rejects_malformed_snapshot_inline() {
        // The validation rule (used by bind_worker_to_snapshot) rejects anything
        // outside [0-9A-Fa-f-]; a quote-injection attempt must be refused.
        let bad = "00000003'; DROP TABLE items; --";
        let ok = bad.bytes().all(|b| b.is_ascii_hexdigit() || b == b'-');
        assert!(!ok, "injection-shaped id must be rejected");
        let good = "00000003-0000001B-1";
        assert!(good.bytes().all(|b| b.is_ascii_hexdigit() || b == b'-'));
    }
}
