#!/bin/bash
set -e

if [[ "${CI}" ]]; then
    set -x
fi
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${PGSTAC_REPO_DIR:-/opt/src}

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code.

This script is meant to be run inside the dev container.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    echo "Formatting pgstac-migrate..."
    uv run --directory pgstac-migrate --group dev ruff check --fix src/pgstac_migrate tests
    uv run --directory pgstac-migrate --group dev ruff format src/pgstac_migrate tests
fi
