#!/bin/bash
set -e

if [[ "${CI}" ]]; then
    set -x
fi
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${PGSTAC_REPO_DIR:-/opt/src}

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code.

This script is meant to be run inside the dev container.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    echo "Formatting pypgstac..."
    ruff check --fix pypgstac/src/pypgstac pypgstac/tests
    ruff format pypgstac/src/pypgstac pypgstac/tests
fi
