#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--db]
Start a console in the dev container

--db: Instead, start a psql console in the database container.
"
}

while [[ "$#" > 0 ]]; do case $1 in
    --db)
        DB_CONSOLE=1
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        shift
        shift
        ;;
    esac; done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    if [[ "${DB_CONSOLE}" ]]; then
        scripts/server --detach

        docker-compose \
            -f docker-compose.yml \
            run --rm \
            database \
            psql postgres://username:password@database:5432/postgis

        exit 0
    fi

    # Run database migrations
    docker-compose \
        -f docker-compose.yml \
        run --rm dev \
        /bin/bash

fi
