#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code in this project

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker-compose  \
        run --rm \
        dev scripts/bin/format;
fi
