#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Installs pypgstac locally.

Creates a local pypgstac.egg-info, which is required
even for docker development.
This is because the entire source tree gets mounted
into the container, and without a local egg-info pypgstac
will not be found inside the docker environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    pushd pypgstac
    pip install -e .
    popd
fi
