#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run migrations against the development database.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    # Run database migrations
    docker-compose up -d pgstac
    docker-compose \
        exec pgstac \
        bash -c "pypgstac pgready && pypgstac migrate --debug"

fi
