#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -e

if [[ "${CI}" ]]; then
    set -x
fi
function usage() {
    echo -n \
        "Usage: $(basename "$0") <--build> <--no-cache> <script>
        script options: format, test, makemigration, stageversion
        "
exit 1
}

[ "$#" -eq 0 ] && usage
echo "ARGS: $@"
ARGS=($@)
CONTAINER_ARGS=()
VOLUMES=""
for ARG in "${ARGS[@]}"
do
    if [[ $ARG == "--no-cache" ]]; then
        NOBUILD=0
        NOCACHE="--no-cache"
    elif [[ $ARG == "--nobuild" ]]; then
        NOBUILD=1
    elif [[ $ARG == "--nuke" ]]; then
        NUKE=1
    elif [[ $ARG == "--mountmigrations" ]]; then
        VOLUMES="$VOLUMES -v $PWD/src/pgstac/migrations:/src/pgstac/migrations -v $PWD/src/pgstac/sql/999_version.sql:/src/pgstac/sql/999_version.sql -v $PWD/src/pgstac/pgstac.sql:/src/pgstac/pgstac.sql -v $PWD/src/pypgstac/python/pypgstac/version.py:/src/pypgstac/python/pypgstac/version.py -v $PWD/src/pypgstac/pyproject.toml:/src/pypgstac/pyproject.toml"
    elif [[ $ARG == "--mountpy" ]]; then
        VOLUMES="$VOLUMES -v $PWD/src/pypgstac/python/pypgstac:/src/pypgstac/python/pypgstac -v $PWD/src/pypgstac/tests:/src/pypgstac/tests"
    elif [[ $ARG == "--localuser" ]]; then
        USERID="--user $(id -u):$(id -g)"
    else
        echo "Adding $ARG to args"
        CONTAINER_ARGS+=($ARG)
    fi
done

if [[ $NUKE == 1 ]]; then
    echo "Stopping Docker and Removing Volumes and Orphans..."
    docker compose down -v --remove-orphans
fi

if [[ $NOBUILD != 1 ]]; then
    echo "Building docker images..."
    docker compose build $NOCACHE
fi

# Check if pgstac is already running
PGSTAC_RUNNING=$(docker compose ps pgstac --status running -q)

echo "Running pypgstac"
echo "VOLUMES: $VOLUMES"
echo "USER: $USERID"
echo "CARGS: ${CONTAINER_ARGS[@]}"

docker compose run --rm  $VOLUMES $USERID pypgstac "${CONTAINER_ARGS[@]}"

JOBEXITCODE=$?
[[ $PGSTAC_RUNNING == "" ]] && docker compose down --remove-orphans
exit $JOBEXITCODE
