#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Sets up this project for development.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    # Check for local install of pypgstac
    if [[ ! -d "./pypgstac/pypgstac.egg-info" ]]; then

        IN_VIRTUAL_ENV=$(python -c "import sys; print(sys.prefix != sys.base_prefix)")
        if [[ "${IN_VIRTUAL_ENV}" == "True" ]]; then
            echo "Installing pypgstac into virtual environment..."
            scripts/install
        else
            echo "ERROR: You must be in a virtual environment to run scripts/setup."
            echo "Otherwise install pypgstac locally with scripts/install before running this script."
            exit 1;
        fi
    fi

    # Build docker containers
    scripts/update

    echo "migrating..."
    scripts/migrate

    echo "Bringing up database..."
    scripts/server --detach

    echo "Ingesting development data..."
    docker-compose \
        -f docker-compose.yml \
        run --rm \
        dev \
        pypgstac load collections \
        /opt/src/test/testdata/collections.ndjson \
        --method upsert

    docker-compose \
        -f docker-compose.yml \
        run --rm \
        dev \
        pypgstac load items \
        /opt/src/test/testdata/items.ndjson \
        --method upsert

    echo "Done."

fi
