#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--skipincremental]
Run database tests

--skipincremental: Skip incremental migration checks.
"
}

SKIPINCREMENTAL=''
while [[ "$#" > 0 ]]; do case $1 in
    --skipincremental)
        SKIPINCREMENTAL='--skipincremental'
        shift
        ;;
    --skipmigrations)
        SKIPMIGRATIONS='--skipmigrations'
        SKIPINCREMENTAL='--skipincremental'
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        shift
        shift
        ;;
    esac; done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    echo "Starting database..."
    scripts/server --detach;

    [ $SKIPMIGRATIONS == '--skipmigrations' ] && scripts/migrate

    echo "Running database tests..."
    docker-compose \
        exec -T \
        database /opt/src/scripts/bin/testdb $SKIPINCREMENTAL $SKIPINCREMENTAL;

    echo "Running pypgstac tests..."
    docker-compose  \
        run --rm \
        dev scripts/bin/test;
fi
