#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..
set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--no-cache]
Builds the docker containers for this project.

--no-cache: Rebuild all containers from scratch.
"
}

# Parse args
NO_CACHE="";
while [[ "$#" > 0 ]]; do case $1 in
    --no-cache) NO_CACHE="--no-cache"; shift;;
    --help) usage; exit 0; shift;;
  *) usage "Unknown parameter passed: $1"; shift; shift;;
esac; done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    echo "==Building images..."

    docker-compose build ${NO_CACHE}

fi
