name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
  pull_request:
    paths:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'

jobs:
  docs:
    name: ${{ github.event_name == 'push' && 'Deploy docs' || 'Build docs' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material mkdocs-jupyter pandas seaborn folium

      - name: Build docs
        if: github.event_name == 'pull_request'
        run: mkdocs build -f docs/mkdocs.yml

      - name: Deploy docs
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml
